run:
  timeout: 5m
  tests: true
  concurrency: 4

linters:
  enable:
    - govet         # finds suspicious constructs
    - errcheck      # checks for ignored errors
    - staticcheck   # powerful bug finder
    - gosimple      # suggests simpler code
    - ineffassign   # unused assignments
    - gosec         # security issues
    - revive        # style guide & performance
    - unparam       # unused function parameters
    - prealloc      # suggest slice preallocation
    - goconst       # find repeated strings/numbers
  disable:
    - lll           # disable long line check (optional)
    - godox         # disable TODO/FIXME warnings (optional)

linters-settings:
  errcheck:
    check-type-assertions: true
  gosec:
    excludes:
      - G104 # ignore unhandled errors in some cases
  revive:
    rules:
      - name: var-naming
        arguments: [["ID", "HTTP", "JSON"]]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck # allow ignoring errors in tests
  max-issues-per-linter: 50
  max-same-issues: 3

output:
  sort-results: true
  format: colored-line-number
